version: '3.7'
services:
  ## --------------------------- ORION (UNICHAT) --------------------------- ##

  unichat_app:
    image: ghcr.io/alexbuzatto/unichateclick:v5.0.0
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: >
      sh -c "echo 'Rails.application.config.active_storage.variant_processor = :mini_magick' > /app/config/initializers/active_storage.rb && bundle exec rails db:unichat_prepare && bundle exec rails db:seed && bundle exec rails s -p 3000 -b 0.0.0.0"
    entrypoint: docker/entrypoints/rails.sh
    volumes:
      - unichat_storage:/app/storage
      # - unichat_public:/app/public
      - unichat_mailer:/app/app/views/devise/mailer
      - unichat_mailers:/app/app/views/mailers

    networks:
      - eclick

    environment:
      - INSTALLATION_NAME=Unichat
      - BRAND_NAME=Unichat
      - SECRET_KEY_BASE=fdceee53290992293fd29603c373cd2f
      - FRONTEND_URL=https://unichat.eclicksolucoes.com.br
      - FORCE_SSL=true
      - DEFAULT_LOCALE=pt_BR
      - TZ=America/Sao_Paulo
      - REDIS_URL=redis://unichat_redis:6379
      - POSTGRES_HOST=pgvector
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=0cfde4fe45c8b679cfd16983daa4b7bc
      - POSTGRES_DATABASE=unichat
      - ACTIVE_STORAGE_SERVICE=local
      - MAILER_SENDER_EMAIL=alexbsbb3@gmail.com <alexbsbb3@gmail.com>
      - SMTP_DOMAIN=gmail.com
      - SMTP_ADDRESS=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_SSL=true
      - SMTP_USERNAME=alexbsbb3@gmail.com
      - SMTP_PASSWORD=ooqd cklm qfdf ecwk
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=peer
      - MAILER_INBOUND_EMAIL_DOMAIN=alexbsbb3@gmail.com
      - SIDEKIQ_CONCURRENCY=10
      - RACK_TIMEOUT_SERVICE_TIMEOUT=0
      - RAILS_MAX_THREADS=5
      - WEB_CONCURRENCY=2
      - ENABLE_RACK_ATTACK=false
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - RAILS_LOG_TO_STDOUT=true
      - USE_INBOX_AVATAR_FOR_BOT=true
      - ENABLE_ACCOUNT_SIGNUP=false
      - VITE_RUBY_SKIP_COMPATIBILITY_CHECK=true
      - DISABLE_RUBY_PLUGIN=true

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.unichat_app.rule=Host(`unichat.eclicksolucoes.com.br`)
        - traefik.http.routers.unichat_app.entrypoints=websecure
        - traefik.http.routers.unichat_app.tls.certresolver=letsencryptresolver
        - traefik.http.routers.unichat_app.priority=1
        - traefik.http.routers.unichat_app.service=unichat_app
        - traefik.http.services.unichat_app.loadbalancer.server.port=3000
        - traefik.http.services.unichat_app.loadbalancer.passHostHeader=true
        - traefik.http.middlewares.unichat_ssl.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.unichat_app.middlewares=unichat_ssl

  unichat_sidekiq:
    image: ghcr.io/alexbuzatto/unichateclick:v5.0.0
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - unichat_storage:/app/storage
      # - unichat_public:/app/public
      - unichat_mailer:/app/app/views/devise/mailer
      - unichat_mailers:/app/app/views/mailers
    networks:
      - eclick
    environment:
      - INSTALLATION_NAME=Unichat
      - BRAND_NAME=Unichat
      - SECRET_KEY_BASE=fdceee53290992293fd29603c373cd2f
      - FRONTEND_URL=https://unichat.eclicksolucoes.com.br
      - FORCE_SSL=true
      - DEFAULT_LOCALE=pt_BR
      - TZ=America/Sao_Paulo
      - REDIS_URL=redis://unichat_redis:6379
      - POSTGRES_HOST=pgvector
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=0cfde4fe45c8b679cfd16983daa4b7bc
      - POSTGRES_DATABASE=unichat
      - ACTIVE_STORAGE_SERVICE=local
      - MAILER_SENDER_EMAIL=alexbsbb3@gmail.com <alexbsbb3@gmail.com>
      - SMTP_DOMAIN=gmail.com
      - SMTP_ADDRESS=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_SSL=true
      - SMTP_USERNAME=alexbsbb3@gmail.com
      - SMTP_PASSWORD=ooqd cklm qfdf ecwk
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=peer
      - MAILER_INBOUND_EMAIL_DOMAIN=alexbsbb3@gmail.com
      - SIDEKIQ_CONCURRENCY=10
      - RACK_TIMEOUT_SERVICE_TIMEOUT=0
      - RAILS_MAX_THREADS=5
      - WEB_CONCURRENCY=2
      - ENABLE_RACK_ATTACK=false
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - RAILS_LOG_TO_STDOUT=true
      - USE_INBOX_AVATAR_FOR_BOT=true
      - ENABLE_ACCOUNT_SIGNUP=false
      - VITE_RUBY_SKIP_COMPATIBILITY_CHECK=true
      - DISABLE_RUBY_PLUGIN=true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 1024M

  unichat_redis:
    image: redis:latest
    command: ['redis-server', '--appendonly', 'yes', '--port', '6379']
    volumes:
      - unichat_redis_data:/data
    networks:
      - eclick
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 1024M

volumes:
  unichat_storage:
    external: true
    name: unichat_storage
  unichat_public:
    external: true
    name: unichat_public
  unichat_mailer:
    external: true
    name: unichat_mailer
  unichat_mailers:
    external: true
    name: unichat_mailers
  unichat_redis_data:
    external: true
    name: unichat_redis_data

networks:
  eclick:
    external: true
    name: eclick
